homepage: "https://boringssl.googlesource.com/boringssl/"
language: c++
primary_contact: "bublaq@gmail.com"
auto_ccs:
 - "rnowicki82@gmail.com"
sanitizers:
- address
- undefined
- memory
fuzzing_engines:
 -libfuzzer
main_repo: 'https://boringssl.googlesource.com/boringssl'
