homepage: "https://boringssl.googlesource.com/boringssl/"
language: c++
primary_contact: "roman.necel@intel.com"
auto_ccs:
 - "rafal.nowick@intel.com"
sanitizers:
- address
- undefined
- memory
fuzzing_engines:
- libfuzzer
main_repo: 'https://boringssl.googlesource.com/boringssl'
